#!/usr/bin/env bash
# graph-server-agent.sh — run the HCE graph service as a macOS LaunchAgent.
#
# Mirrors dev-dashboard/scripts/dashboard-agent.sh's pattern (generated
# runtime-node-resolving wrapper + plist, machine-local dirs, same verbs).
# NOT registered with dev-dashboard itself: this is a background data API,
# not something you open a browser tab on, which is what that tool's
# registry is for.
#
# Usage:
#   scripts/graph-server-agent.sh install     # write wrapper + plist, load + start
#   scripts/graph-server-agent.sh uninstall   # stop + unload + remove
#   scripts/graph-server-agent.sh restart     # kickstart the running agent
#   scripts/graph-server-agent.sh status      # loaded? running? which PID?
#   scripts/graph-server-agent.sh logs        # tail stdout + stderr

set -euo pipefail

LABEL="com.hce.graphserver"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
DOMAIN="gui/$(id -u)"
TARGET="${DOMAIN}/${LABEL}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Machine-local dirs (NOT in the synced repo) — same directory store.js and
# crypto.js default to for graph.json/field-key.json, so everything this
# service owns lives in one place.
SUPPORT_DIR="$HOME/Library/Application Support/human-connection-engine"
WRAPPER="$SUPPORT_DIR/graph-server-launch.sh"
LOG_DIR="$HOME/Library/Logs/human-connection-engine"

write_wrapper() {
  mkdir -p "$SUPPORT_DIR"
  cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# GENERATED by graph-server-agent.sh. Resolves node at runtime so nvm version
# switches don't break the LaunchAgent. Re-run install to refresh SERVER_DIR.
SERVER_DIR="${SERVER_DIR}"
cd "\$SERVER_DIR" || exit 1

if [[ -s "\$HOME/.nvm/nvm.sh" ]]; then
  export NVM_DIR="\$HOME/.nvm"
  . "\$NVM_DIR/nvm.sh" --no-use >/dev/null 2>&1 || true
  nvm use default >/dev/null 2>&1 || true
fi

NODE_BIN="\$(command -v node || true)"
if [[ -z "\$NODE_BIN" ]]; then
  for c in /opt/homebrew/bin/node /usr/local/bin/node /usr/bin/node; do
    [[ -x "\$c" ]] && NODE_BIN="\$c" && break
  done
fi
if [[ -z "\$NODE_BIN" ]]; then
  echo "[hce-graph-server] FATAL: node not found via nvm, Homebrew, or system." >&2
  exit 1
fi

echo "[hce-graph-server] \$(date '+%F %T') using node \$("\$NODE_BIN" --version 2>/dev/null) at \$NODE_BIN"
exec "\$NODE_BIN" src/server.js
EOF
  chmod +x "$WRAPPER"
  echo "wrote wrapper: $WRAPPER"
}

write_plist() {
  mkdir -p "$LOG_DIR" "$(dirname "$PLIST")"
  cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>

  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${WRAPPER}</string>
  </array>

  <key>WorkingDirectory</key>
  <string>${SERVER_DIR}</string>

  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    <key>NODE_ENV</key>
    <string>production</string>
  </dict>

  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>10</integer>

  <key>StandardOutPath</key>
  <string>${LOG_DIR}/graph-server.out.log</string>
  <key>StandardErrorPath</key>
  <string>${LOG_DIR}/graph-server.err.log</string>
</dict>
</plist>
EOF
  echo "wrote plist:   $PLIST"
}

cmd_install() {
  write_wrapper
  write_plist
  launchctl bootout "$TARGET" 2>/dev/null || true
  launchctl bootstrap "$DOMAIN" "$PLIST"
  launchctl enable "$TARGET" 2>/dev/null || true
  echo "installed and started: $LABEL"
  cmd_status
}

cmd_uninstall() {
  launchctl bootout "$TARGET" 2>/dev/null || true
  rm -f "$PLIST"
  echo "uninstalled: $LABEL"
}

cmd_restart() { launchctl kickstart -k "$TARGET"; echo "restarted: $LABEL"; }

cmd_status() {
  if launchctl print "$TARGET" >/dev/null 2>&1; then
    launchctl print "$TARGET" | grep -E '^\s*(state|pid) =' || true
  else
    echo "$LABEL is not loaded. Run: $0 install"
  fi
}

cmd_logs() {
  touch "$LOG_DIR/graph-server.out.log" "$LOG_DIR/graph-server.err.log"
  tail -n 40 -f "$LOG_DIR/graph-server.out.log" "$LOG_DIR/graph-server.err.log"
}

case "${1:-}" in
  install)   cmd_install ;;
  uninstall) cmd_uninstall ;;
  restart)   cmd_restart ;;
  status)    cmd_status ;;
  logs)      cmd_logs ;;
  *) echo "usage: $0 {install|uninstall|restart|status|logs}" >&2; exit 2 ;;
esac
